site_name: Documentation
site_url: https://www.fivenorthgroup.com/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Inter Tight
    code: Red Hat Mono
  logo: assets/logo_infrastructure_for-dark-bg.svg
  favicon: assets/favicon.jpg
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: black

    # Light Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: black

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

copyright: Copyright &copy; 2025 Five North Group