site_name: Operating Documents
site_url: https://www.fivenorthgroup.com/
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  font:
    text: Inter Tight
    code: Red Hat Mono
  logo: assets/logo_infrastructure_for-dark-bg.svg
  favicon: assets/favicon.jpg
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky

    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips

    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  palette:
    # Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: black

    # Light Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: black
      accent: black


plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: "pymdownx.details"
          class: "details"
          format: "!!python/name:pymdownx.superfences.fence_details_format"
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - toc:
      permalink: true

copyright: Copyright &copy; 2025 Five North Group

nav:
  - 5N Infra:
    - index.md
    - Hosted Node: hosted-node/hosted-node-access.md
    - Sponsor:
      - IP Restriction: sponsored-node/check-ip-allow-status.md
      - Network Param: sponsored-node/network-parameters.md
  - 5N Dashboard:
    - Overview: 5n-dashboard/introduction.md
    - Installation: 5n-dashboard/install.md
    - Release: 5n-dashboard/release.md
    - Guide:
      - DAR management: 5n-dashboard/dar-management.md
      - User management: 5n-dashboard/user-management.md
      - Party Management: 5n-dashboard/party-management.md
      - Shell: 5n-dashboard/shell.md
