[project]
name = "docs"
version = "0.1.0"
description = "FiveNorth Public Docs Site"
readme = "README.md"
requires-python = ">=3.12.5"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
